package com.tt.eggs.drawable

import android.content.Context
import android.graphics.*
import android.graphics.drawable.Drawable
import androidx.core.content.ContextCompat
import com.tt.eggs.R
import com.tt.eggs.classes.Functions
import com.tt.eggs.classes.Static

class WolfLeft (private val context: Context, private val width: Double, private val wolf:Int): Drawable() {
    private val paint = Paint()
    private val unit = width/100



    override fun draw(canvas: Canvas) {

        paint.color = ContextCompat.getColor(context, R.color.shadow)

        if(wolf==Static.WOLF_SHADOW){
            paint.color = ContextCompat.getColor(context, R.color.shadow)
        }else{
            paint.color = ContextCompat.getColor(context, R.color.black)
        }
        drawBody(canvas)


        if(wolf==Static.WOLF_DOWN){
            paint.color = ContextCompat.getColor(context, R.color.black)
        }else{
            paint.color = ContextCompat.getColor(context, R.color.shadow)
        }
        drawDown(canvas)

        if(wolf==Static.WOLF_UP){
            paint.color = ContextCompat.getColor(context, R.color.black)
        }else{
            paint.color = ContextCompat.getColor(context, R.color.shadow)
        }
        drawUp(canvas)


    }

    private fun drawUp(canvas: Canvas){
        drawArmsUp(canvas)
        drawBasketUp(canvas)
    }

    private fun drawDown(canvas: Canvas){
        drawBasketDown(canvas)
        drawArmsDown(canvas)
        drawBasketDownHandle(canvas)
    }

    private fun drawBody(canvas: Canvas){
        drawHair(canvas)
        drawShirt(canvas)
        drawLegs(canvas)
        drawPants(canvas)
        drawEar(canvas)
        drawHair2(canvas)
        drawFace(canvas)
        drawMouth(canvas)
        drawNose(canvas)
        drawEyes(canvas)
    }

    private fun drawHair(canvas: Canvas){
        paint.strokeWidth = (unit/2).toFloat()
        paint.style = Paint.Style.FILL_AND_STROKE

        val a = Point((width*0.5).toInt(), (width*0.1).toInt())
        val b = Point((width*0.48).toInt(), (width*0.09).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*5,true)
        val c = Point((width*0.52).toInt(), (width*0.05).toInt())
        val d = Point((width*0.68).toInt(), (width*0.13).toInt())
        val e = Point((width*0.68).toInt(), (width*0.17).toInt())
        val f = Point((width*0.73).toInt(), (width*0.2).toInt())
        val g = Point((width*0.81).toInt(), (width*0.26).toInt())
        val radiusFG = Functions.curvedPath(f,g,unit*12,true)
        val h = Point((width*0.77).toInt(), (width*0.23).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit,false)
        val i = Point((width*0.79).toInt(), (width*0.27).toInt())
        val j = Point((width*0.79).toInt(), (width*0.37).toInt())
        val radiusIJ = Functions.curvedPath(i,j,unit*3,true)
        val k = Point((width*0.765).toInt(), (width*0.29).toInt())
        val radiusJK = Functions.curvedPath(j,k,unit*2,false)
        val l = Point((width*0.75).toInt(), (width*0.38).toInt())
        val radiusKL = Functions.curvedPath(k,l,unit*1,true)
        val m = Point((width*0.67).toInt(), (width*0.38).toInt())
        val radiusLM = Functions.curvedPath(l,m,unit*2,false)
        val n = Point((width*0.67).toInt(), (width*0.31).toInt())
        val radiusMN = Functions.curvedPath(m,n,unit*3,false)
        val o = Point((width*0.66).toInt(), (width*0.275).toInt())
        val radiusNO = Functions.curvedPath(n,o,unit*2,false)
        val p = Point((width*0.66).toInt(), (width*0.2).toInt())
        val radiusOP = Functions.curvedPath(o,p,unit*3,false)
        val r = Point((width*0.55).toInt(), (width*0.14).toInt())
        val s = Point((width*0.51).toInt(), (width*0.16).toInt())
        val radiusRS = Functions.curvedPath(r,s,unit*2,false)
        val t = Point((width*0.495).toInt(), (width*0.16).toInt())
        val radiusST = Functions.curvedPath(s,t,unit*2,true)
        val u = Point((width*0.54).toInt(), (width*0.11).toInt())
        val radiusTU = Functions.curvedPath(t,u,unit*2,true)
        val v = Point((width*0.54).toInt(), (width*0.09).toInt())
        val radiusUV = Functions.curvedPath(u,v,unit*2,false)
        val radiusVA = Functions.curvedPath(v,a,unit,false)



        val path = Path()
        path.moveTo(a.x.toFloat(), a.y.toFloat())
        path.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        path.lineTo(c.x.toFloat(), c.y.toFloat())
        path.lineTo(d.x.toFloat(), d.y.toFloat())
        path.lineTo(e.x.toFloat(), e.y.toFloat())
        path.lineTo(f.x.toFloat(), f.y.toFloat())
        path.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        path.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        path.lineTo(i.x.toFloat(), i.y.toFloat())
        path.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        path.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        path.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKL.x,radiusKL.y, l.x.toFloat(), l.y.toFloat())
        path.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        path.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        path.cubicTo(n.x.toFloat(), n.y.toFloat(),radiusNO.x,radiusNO.y, o.x.toFloat(), o.y.toFloat())
        path.cubicTo(o.x.toFloat(), o.y.toFloat(),radiusOP.x,radiusOP.y, p.x.toFloat(), p.y.toFloat())
        path.lineTo(r.x.toFloat(), r.y.toFloat())
        path.cubicTo(r.x.toFloat(), r.y.toFloat(),radiusRS.x,radiusRS.y, s.x.toFloat(), s.y.toFloat())
        path.cubicTo(s.x.toFloat(), s.y.toFloat(),radiusST.x,radiusST.y, t.x.toFloat(), t.y.toFloat())
        path.cubicTo(t.x.toFloat(), t.y.toFloat(),radiusTU.x,radiusTU.y, u.x.toFloat(), u.y.toFloat())
        path.cubicTo(u.x.toFloat(), u.y.toFloat(),radiusUV.x,radiusUV.y, v.x.toFloat(), v.y.toFloat())
        path.cubicTo(v.x.toFloat(), v.y.toFloat(),radiusVA.x,radiusVA.y, a.x.toFloat(), a.y.toFloat())
        path.close()

        canvas.drawPath(path,paint)
    }

    private fun drawShirt(canvas: Canvas){
        paint.style = Paint.Style.FILL_AND_STROKE
        val path1 = Path()

        val a = Point((width*0.73).toInt(), (width*0.375).toInt())
        val b = Point((width*0.73).toInt(), (width*0.42).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*2,false)
        val c = Point((width*0.73).toInt(), (width*0.44).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit,true)
        val d = Point((width*0.65).toInt(), (width*0.55).toInt())
        val e = Point((width*0.63).toInt(), (width*0.63).toInt())
        val f = Point((width*0.6).toInt(), (width*0.66).toInt())
        val g = Point((width*0.58).toInt(), (width*0.67).toInt())
        val radiusFG = Functions.curvedPath(f,g,unit*2,false)
        val h = Point((width*0.49).toInt(), (width*0.66).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit,false)
        val i = Point((width*0.47).toInt(), (width*0.61).toInt())
        val radiusHI = Functions.curvedPath(h,i,unit*3,true)
        val j = Point((width*0.51).toInt(), (width*0.55).toInt())
        val k = Point((width*0.54).toInt(), (width*0.49).toInt())
        val radiusJK = Functions.curvedPath(j,k,unit,true)
        val l = Point((width*0.56).toInt(), (width*0.44).toInt())
        val radiusKL = Functions.curvedPath(k,l,unit,false)
        val m = Point((width*0.6).toInt(), (width*0.41).toInt())
        val radiusLM = Functions.curvedPath(l,m,unit*2,true)
        val n = Point((width*0.605).toInt(), (width*0.45).toInt())
        val radiusMN = Functions.curvedPath(m,n,unit*2,true)
        val o = Point((width*0.58).toInt(), (width*0.5).toInt())
        val p = Point((width*0.565).toInt(), (width*0.535).toInt())
        val radiusOP = Functions.curvedPath(o,p,unit*2,false)
        val q = Point((width*0.63).toInt(), (width*0.5).toInt())
        val radiusPQ = Functions.curvedPath(p,q,unit*3,false)
        val r = Point((width*0.68).toInt(), (width*0.41).toInt())
        val s = Point((width*0.69).toInt(), (width*0.39).toInt())
        val radiusRS = Functions.curvedPath(r,s,unit,true)
        val t = Point((width*0.69).toInt(), (width*0.37).toInt())
        val radiusST = Functions.curvedPath(s,t,unit,false)

        path1.moveTo(a.x.toFloat(), a.y.toFloat())
        path1.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        path1.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        path1.lineTo(d.x.toFloat(), d.y.toFloat())
        path1.lineTo(e.x.toFloat(), e.y.toFloat())
        path1.lineTo(f.x.toFloat(), f.y.toFloat())
        path1.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        path1.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        path1.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        path1.lineTo(j.x.toFloat(), j.y.toFloat())
        path1.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        path1.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKL.x,radiusKL.y, l.x.toFloat(), l.y.toFloat())
        path1.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        path1.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        path1.lineTo(o.x.toFloat(), o.y.toFloat())
        path1.cubicTo(o.x.toFloat(), o.y.toFloat(),radiusOP.x,radiusOP.y, p.x.toFloat(), p.y.toFloat())
        path1.cubicTo(p.x.toFloat(), p.y.toFloat(),radiusPQ.x,radiusPQ.y, q.x.toFloat(), q.y.toFloat())
        path1.lineTo(r.x.toFloat(), r.y.toFloat())
        path1.cubicTo(r.x.toFloat(), r.y.toFloat(),radiusRS.x,radiusRS.y, s.x.toFloat(), s.y.toFloat())
        path1.cubicTo(s.x.toFloat(), s.y.toFloat(),radiusST.x,radiusST.y, t.x.toFloat(), t.y.toFloat())
        path1.close()

        canvas.drawPath(path1,paint)

    }

    private fun drawLegs(canvas: Canvas){

        paint.style = Paint.Style.STROKE
        paint.strokeWidth = (unit*1.5).toFloat()
        val pathLegs = Path()

        val a= Point((width*0.62).toInt(), (width*0.62).toInt())
        val b= Point((width*0.78).toInt(), (width*0.72).toInt())
        val c = Point((width*0.79).toInt(), (width*0.76).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit*2,true)
        val d = Point((width*0.75).toInt(), (width*0.855).toInt())
        val e = Point((width*0.68).toInt(), (width*0.9).toInt())
        val f = Point((width*0.84).toInt(), (width*0.84).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit*4,true)
        val g = Point((width*0.85).toInt(), (width*0.87).toInt())
        val radiusFG = Functions.curvedPath(f,g,unit*4,true)
        val h = Point((width*0.68).toInt(), (width*0.94).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit*4,true)
        val radiusHE = Functions.curvedPath(h,e,unit*3,true)
        val i = Point((width*0.73).toInt(), (width*0.78).toInt())
        val j = Point((width*0.71).toInt(), (width*0.75).toInt())
        val radiusIJ = Functions.curvedPath(i,j,unit*3,false)
        val k = Point((width*0.54).toInt(), (width*0.73).toInt())
        val l = Point((width*0.435).toInt(), (width*0.77).toInt())
        val m = Point((width*0.55).toInt(), (width*0.86).toInt())
        val n = Point((width*0.53).toInt(), (width*0.95).toInt())
        val radiusMN = Functions.curvedPath(m,n,unit*9,true)
        val o = Point((width*0.36).toInt(), (width*0.93).toInt())
        val radiusNO = Functions.curvedPath(n,o,unit*4,true)
        val p = Point((width*0.34).toInt(), (width*0.87).toInt())
        val radiusOP = Functions.curvedPath(o,p,unit*4,true)
        val q = Point((width*0.48).toInt(), (width*0.885).toInt())
        val radiusPQ = Functions.curvedPath(p,q,unit*3,true)
        val r = Point((width*0.49).toInt(), (width*0.86).toInt())
        val radiusQR = Functions.curvedPath(q,r,unit*6,false)
        val s = Point((width*0.36).toInt(), (width*0.785).toInt())
        val t = Point((width*0.35).toInt(), (width*0.74).toInt())
        val radiusST = Functions.curvedPath(s,t,unit*4,true)
        val u = Point((width*0.49).toInt(), (width*0.64).toInt())
        val radiusTU = Functions.curvedPath(t,u,unit,true)

        pathLegs.moveTo(a.x.toFloat(), a.y.toFloat())
        pathLegs.lineTo(b.x.toFloat(), b.y.toFloat())
        pathLegs.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathLegs.lineTo(d.x.toFloat(), d.y.toFloat())
        pathLegs.moveTo(e.x.toFloat(), e.y.toFloat())
        pathLegs.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathLegs.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathLegs.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        pathLegs.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHE.x,radiusHE.y, e.x.toFloat(), e.y.toFloat())
        pathLegs.lineTo(i.x.toFloat(), i.y.toFloat())
        pathLegs.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        pathLegs.lineTo(k.x.toFloat(), k.y.toFloat())
        pathLegs.lineTo(l.x.toFloat(), l.y.toFloat())
        pathLegs.lineTo(m.x.toFloat(), m.y.toFloat())
        pathLegs.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        pathLegs.cubicTo(n.x.toFloat(), n.y.toFloat(),radiusNO.x,radiusNO.y, o.x.toFloat(), o.y.toFloat())
        pathLegs.cubicTo(o.x.toFloat(), o.y.toFloat(),radiusOP.x,radiusOP.y, p.x.toFloat(), p.y.toFloat())
        pathLegs.cubicTo(p.x.toFloat(), p.y.toFloat(),radiusPQ.x,radiusPQ.y, q.x.toFloat(), q.y.toFloat())
        pathLegs.cubicTo(q.x.toFloat(), q.y.toFloat(),radiusQR.x,radiusQR.y, r.x.toFloat(), r.y.toFloat())
        pathLegs.lineTo(s.x.toFloat(), s.y.toFloat())
        pathLegs.cubicTo(s.x.toFloat(), s.y.toFloat(),radiusST.x,radiusST.y, t.x.toFloat(), t.y.toFloat())
        pathLegs.cubicTo(t.x.toFloat(), t.y.toFloat(),radiusTU.x,radiusTU.y, u.x.toFloat(), u.y.toFloat())

        canvas.drawPath(pathLegs,paint)



    }

    private fun drawPants(canvas:Canvas){
        val a = Point((width*0.45).toInt(), (width*0.76).toInt())
        val b = Point((width*0.37).toInt(), (width*0.71).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*2,false)
        val c = Point((width*0.5).toInt(), (width*0.6).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit*2,false)
        val d = Point((width*0.38).toInt(), (width*0.87).toInt())
        val e = Point((width*0.41).toInt(), (width*0.92).toInt())
        val radiusDE = Functions.curvedPath(d,e,unit*4,false)
        val f = Point((width*0.58).toInt(), (width*0.9).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit*3,false)
        val g = Point((width*0.68).toInt(), (width*0.94).toInt())
        val h = Point((width*0.855).toInt(), (width*0.86).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit*3,true)
        val i = Point((width*0.68).toInt(), (width*0.745).toInt())
        val j = Point((width*0.73).toInt(), (width*0.67).toInt())
        val radiusIJ = Functions.curvedPath(i,j,unit,true)
        val k = Point((width*0.6).toInt(), (width*0.6).toInt())
        val radiusJK = Functions.curvedPath(j,k,unit,true)
        val l = Point((width*0.65).toInt(), (width*0.63).toInt())
        val m = Point((width*0.73).toInt(), (width*0.58).toInt())
        val radiusLM = Functions.curvedPath(l,m,unit,true)
        val n = Point((width*0.76).toInt(), (width*0.6).toInt())
        val radiusMN = Functions.curvedPath(m,n,unit*3,true)
        val o = Point((width*0.69).toInt(), (width*0.65).toInt())
        val radiusNO = Functions.curvedPath(n,o,unit*2,true)

        val pathPants = Path()
        pathPants.moveTo(a.x.toFloat(), a.y.toFloat())
        pathPants.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathPants.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathPants.moveTo(d.x.toFloat(), d.y.toFloat())
        pathPants.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        pathPants.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathPants.moveTo(g.x.toFloat(), g.y.toFloat())
        pathPants.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        pathPants.moveTo(i.x.toFloat(), i.y.toFloat())
        pathPants.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        pathPants.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathPants.moveTo(l.x.toFloat(), l.y.toFloat())
        pathPants.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        pathPants.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        pathPants.cubicTo(n.x.toFloat(), n.y.toFloat(),radiusNO.x,radiusNO.y, o.x.toFloat(), o.y.toFloat())

        canvas.drawPath(pathPants,paint)
    }

    private fun drawEar(canvas: Canvas){
        paint.strokeWidth = (unit*1.5).toFloat()
        val a = Point((width*0.68).toInt(), (width*0.17).toInt())
        val b = Point((width*0.77).toInt(), (width*0.05).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*6,true)
        val c = Point((width*0.73).toInt(), (width*0.2).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit*7,true)
        val d = Point((width*0.70).toInt(), (width*0.18).toInt())
        val e = Point((width*0.74).toInt(), (width*0.13).toInt())
        val radiusDE = Functions.curvedPath(d,e,unit*2,true)
        val f = Point((width*0.71).toInt(), (width*0.19).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit*2,true)
        val g = Point((width*0.56).toInt(), (width*0.08).toInt())
        val h = Point((width*0.64).toInt(), (width*0.08).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit*5,true)
        val i = Point((width*0.7).toInt(), (width*0.09).toInt())
        val j = Point((width*0.68).toInt(), (width*0.12).toInt())
        val k = Point((width*0.62).toInt(), (width*0.105).toInt())
        val l = Point((width*0.64).toInt(), (width*0.08).toInt())
        val m = Point((width*0.63).toInt(), (width*0.08).toInt())
        val n = Point((width*0.61).toInt(), (width*0.105).toInt())
        val radiusHI = Functions.curvedPath(h,i,unit*3,true)
        val o = Point((width*0.67).toInt(), (width*0.07).toInt())
        val p = Point((width*0.7).toInt(), (width*0.08).toInt())
        val radiusOP = Functions.curvedPath(o,p,unit*8,true)



        val pathEar = Path()
        pathEar.moveTo(a.x.toFloat(), a.y.toFloat())
        pathEar.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathEar.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathEar.moveTo(d.x.toFloat(), d.y.toFloat())
        pathEar.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        pathEar.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathEar.moveTo(g.x.toFloat(), g.y.toFloat())
        pathEar.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        pathEar.lineTo(i.x.toFloat(), i.y.toFloat())
        pathEar.lineTo(j.x.toFloat(), j.y.toFloat())
        pathEar.lineTo(k.x.toFloat(), k.y.toFloat())
        pathEar.lineTo(l.x.toFloat(), l.y.toFloat())
        pathEar.lineTo(m.x.toFloat(), m.y.toFloat())
        pathEar.lineTo(n.x.toFloat(), n.y.toFloat())
        pathEar.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathEar.moveTo(o.x.toFloat(), o.y.toFloat())
        pathEar.cubicTo(o.x.toFloat(), o.y.toFloat(),radiusOP.x,radiusOP.y, p.x.toFloat(), p.y.toFloat())

        canvas.drawPath(pathEar,paint)

    }

    private fun drawHair2(canvas:Canvas){
        paint.style = Paint.Style.FILL_AND_STROKE
        paint.strokeWidth = (unit*0.5).toFloat()
        val a = Point((width*0.55).toInt(), (width*0.14).toInt())
        val b = Point((width*0.525).toInt(), (width*0.21).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*2,false)
        val c = Point((width*0.54).toInt(), (width*0.21).toInt())
        val d = Point((width*0.57).toInt(), (width*0.18).toInt())
        val radiusCD = Functions.curvedPath(c,d,unit*4,true)
        val e = Point((width*0.61).toInt(), (width*0.2).toInt())
        val radiusDE = Functions.curvedPath(d,e,unit*5,true)
        val f = Point((width*0.63).toInt(), (width*0.21).toInt())
        val g = Point((width*0.68).toInt(), (width*0.17).toInt())

        val path2 = Path()
        path2.moveTo(a.x.toFloat(), a.y.toFloat())
        path2.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        path2.lineTo(c.x.toFloat(), c.y.toFloat())
        path2.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        path2.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        path2.lineTo(f.x.toFloat(), f.y.toFloat())
        path2.lineTo(g.x.toFloat(), g.y.toFloat())
        path2.close()

        canvas.drawPath(path2,paint)

    }

    private fun drawFace(canvas:Canvas){
        paint.style = Paint.Style.STROKE
        paint.strokeWidth = (unit*1.5).toFloat()

        val a = Point((width*0.58).toInt(), (width*0.22).toInt())
        val b = Point((width*0.63).toInt(), (width*0.21).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*4,true)
        val c = Point((width*0.585).toInt(), (width*0.24).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit*10,true)
        val d = Point((width*0.525).toInt(), (width*0.23).toInt())
        val radiusCD = Functions.curvedPath(c,d,unit*6,false)
        val e = Point((width*0.565).toInt(), (width*0.28).toInt())
        val radiusEA = Functions.curvedPath(e,a,unit*3,false)
        val f = Point((width*0.53).toInt(), (width*0.28).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit*4,false)
        val g = Point((width*0.41).toInt(), (width*0.26).toInt())
        val radiusFG = Functions.curvedPath(f,g,unit*8,false)
        val h = Point((width*0.42).toInt(), (width*0.31).toInt())
        val i = Point((width*0.43).toInt(), (width*0.37).toInt())
        val radiusHI = Functions.curvedPath(h,i,unit,false)
        val j = Point((width*0.47).toInt(), (width*0.39).toInt())
        val radiusIJ = Functions.curvedPath(i,j,unit,true)
        val k = Point((width*0.51).toInt(), (width*0.4).toInt())
        val radiusJK = Functions.curvedPath(j,k,unit*2,false)
        val l = Point((width*0.58).toInt(), (width*0.36).toInt())
        val radiusKL = Functions.curvedPath(k,l,unit,false)
        val m = Point((width*0.64).toInt(), (width*0.35).toInt())
        val radiusLM = Functions.curvedPath(l,m,unit*2,false)
        val n = Point((width*0.6).toInt(), (width*0.44).toInt())
        val radiusMN = Functions.curvedPath(m,n,unit*2,false)

        val pathFace = Path()
        pathFace.moveTo(a.x.toFloat(), a.y.toFloat())
        pathFace.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathFace.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathFace.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathFace.lineTo(e.x.toFloat(), e.y.toFloat())
        pathFace.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEA.x,radiusEA.y, a.x.toFloat(), a.y.toFloat())
        pathFace.moveTo(e.x.toFloat(), e.y.toFloat())
        pathFace.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathFace.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathFace.lineTo(h.x.toFloat(), h.y.toFloat())
        pathFace.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathFace.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        pathFace.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathFace.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKL.x,radiusKL.y, l.x.toFloat(), l.y.toFloat())
        pathFace.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        pathFace.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())

        canvas.drawPath(pathFace,paint)

    }

    private fun drawMouth(canvas: Canvas){
        paint.style = Paint.Style.FILL_AND_STROKE
        paint.strokeWidth = (unit/2).toFloat()

        val a = Point((width*0.42).toInt(), (width*0.31).toInt())
        val b = Point((width*0.47).toInt(), (width*0.31).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*2,true)
        val c = Point((width*0.47).toInt(), (width*0.35).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit*3,false)
        val radiusCB = Functions.curvedPath(c,b,unit*3,false)
        val d = Point((width*0.59).toInt(), (width*0.3).toInt())
        val radiusBD = Functions.curvedPath(b,d,unit*2,false)
        val e = Point((width*0.61).toInt(), (width*0.32).toInt())
        val radiusDE = Functions.curvedPath(d,e,unit*2,true)
        val f = Point((width*0.58).toInt(), (width*0.34).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit*2,true)
        val g = Point((width*0.48).toInt(), (width*0.37).toInt())
        val radiusFG = Functions.curvedPath(f,g,unit*2,false)
        val h = Point((width*0.43).toInt(), (width*0.36).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit*3,false)
        val radiusHA = Functions.curvedPath(h,a,unit*4,false)

        val path3 = Path()
        path3.moveTo(a.x.toFloat(), a.y.toFloat())
        path3.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        path3.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        path3.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCB.x,radiusCB.y, b.x.toFloat(), b.y.toFloat())
        path3.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBD.x,radiusBD.y, d.x.toFloat(), d.y.toFloat())
        path3.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        path3.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        path3.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        path3.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        path3.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHA.x,radiusHA.y, a.x.toFloat(), a.y.toFloat())
        path3.close()

        canvas.drawPath(path3,paint)

    }

    private fun drawNose(canvas: Canvas){
        val a = Point((width*0.43).toInt(), (width*0.18).toInt())
        val b = Point((width*0.445).toInt(), (width*0.27).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*4,true)
        val c = Point((width*0.41).toInt(), (width*0.24).toInt())
        val radiusCA = Functions.curvedPath(c,a,unit*4,true)

        val pathNose = Path()
        pathNose.moveTo(a.x.toFloat(), a.y.toFloat())
        pathNose.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathNose.lineTo(c.x.toFloat(), c.y.toFloat())
        pathNose.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCA.x,radiusCA.y, a.x.toFloat(), a.y.toFloat())
        pathNose.close()

        canvas.drawPath(pathNose,paint)
    }

    private fun drawEyes(canvas: Canvas){
        paint.style = Paint.Style.FILL_AND_STROKE
        paint.strokeWidth = (unit/2).toFloat()

        var a = Point((width*0.53).toInt(), (width*0.24).toInt())
        var b = Point((width*0.56).toInt(), (width*0.27).toInt())
        var radiusAB = Functions.curvedPath(a,b,unit*4,true)


        val pathEye = Path()
        pathEye.moveTo(a.x.toFloat(), a.y.toFloat())
        pathEye.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathEye.close()

        canvas.drawPath(pathEye,paint)

        a = Point((width*0.59).toInt(), (width*0.23).toInt())
        b = Point((width*0.62).toInt(), (width*0.26).toInt())
        radiusAB = Functions.curvedPath(a,b,unit*4,true)


        val pathEye1 = Path()
        pathEye1.moveTo(a.x.toFloat(), a.y.toFloat())
        pathEye1.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathEye1.close()

        canvas.drawPath(pathEye1,paint)
    }

    private fun drawBasketDown(canvas: Canvas){
        paint.style = Paint.Style.FILL_AND_STROKE
        paint.strokeWidth = (unit/2).toFloat()

        val a = Point((width*0.01).toInt(), (width*0.69).toInt())
        val b = Point((width*0.03).toInt(), (width*0.8).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*2,false)
        val c = Point((width*0.19).toInt(), (width*0.86).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit*7,false)
        val d = Point((width*0.27).toInt(), (width*0.8).toInt())
        val radiusCD = Functions.curvedPath(c,d,unit*2,false)
        val e = Point((width*0.27).toInt(), (width*0.76).toInt())
        val radiusDE = Functions.curvedPath(d,e,unit*2,false)
        val f = Point((width*0.04).toInt(), (width*0.66).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit*4,false)
        val radiusFA = Functions.curvedPath(f,a,unit*3,false)

        val pathBasketDown = Path()
        pathBasketDown.moveTo(a.x.toFloat(), a.y.toFloat())
        pathBasketDown.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathBasketDown.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathBasketDown.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathBasketDown.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        pathBasketDown.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathBasketDown.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFA.x,radiusFA.y, a.x.toFloat(), a.y.toFloat())
        pathBasketDown.close()
        canvas.drawPath(pathBasketDown,paint)

    }

    private fun drawArmsDown(canvas: Canvas){
        paint.style = Paint.Style.STROKE

        paint.strokeWidth = (unit*1.5).toFloat()

        var a = Point((width*0.2).toInt(), (width*0.48).toInt())
        var b = Point((width*0.43).toInt(), (width*0.48).toInt())
        var radiusAB = Functions.curvedPath(a,b,unit,true)
        var c = Point((width*0.43).toInt(), (width*0.51).toInt())
        var radiusBC = Functions.curvedPath(b,c,unit*9,true)
        var d = Point((width*0.33).toInt(), (width*0.515).toInt())
        var radiusCD = Functions.curvedPath(c,d,unit,false)
        var e = Point((width*0.29).toInt(), (width*0.55).toInt())
        var radiusDE = Functions.curvedPath(d,e,unit,false)
        var f = Point((width*0.26).toInt(), (width*0.54).toInt())
        var radiusEF = Functions.curvedPath(e,f,unit*3,true)
        var g = Point((width*0.235).toInt(), (width*0.56).toInt())
        var radiusFG = Functions.curvedPath(f,g,unit,false)
        var h = Point((width*0.21).toInt(), (width*0.55).toInt())
        var radiusGH = Functions.curvedPath(g,h,unit*3,true)
        var i = Point((width*0.2).toInt(), (width*0.55).toInt())
        var radiusHI = Functions.curvedPath(h,i,unit*3,false)
        var j = Point((width*0.175).toInt(), (width*0.55).toInt())
        var radiusIJ = Functions.curvedPath(i,j,unit*5,true)
        var k = Point((width*0.165).toInt(), (width*0.55).toInt())
        var radiusJK = Functions.curvedPath(j,k,unit*3,false)
        var l = Point((width*0.165).toInt(), (width*0.575).toInt())
        var radiusKL = Functions.curvedPath(k,l,unit/2,false)
        var m = Point((width*0.145).toInt(), (width*0.585).toInt())
        var radiusLM = Functions.curvedPath(l,m,unit*3,true)
        var n = Point((width*0.15).toInt(), (width*0.5).toInt())
        var radiusMN = Functions.curvedPath(m,n,unit*3,true)
        val radiusNA = Functions.curvedPath(n,a,unit,true)

        val pathArms = Path()
        pathArms.moveTo(a.x.toFloat(), a.y.toFloat())
        pathArms.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathArms.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathArms.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathArms.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        pathArms.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathArms.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathArms.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        pathArms.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathArms.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        pathArms.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathArms.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKL.x,radiusKL.y, l.x.toFloat(), l.y.toFloat())
        pathArms.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        pathArms.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        pathArms.cubicTo(n.x.toFloat(), n.y.toFloat(),radiusNA.x,radiusNA.y, a.x.toFloat(), a.y.toFloat())

        canvas.drawPath(pathArms,paint)



        a = Point((width*0.35).toInt(), (width*0.575).toInt())
        b = Point((width*0.46).toInt(), (width*0.54).toInt())
        radiusAB = Functions.curvedPath(a,b,unit/2,false)
        c = Point((width*0.47).toInt(), (width*0.565).toInt())
        radiusBC = Functions.curvedPath(b,c,unit*5,true)
        d = Point((width*0.4).toInt(), (width*0.595).toInt())
        radiusCD = Functions.curvedPath(c,d,unit/2,true)
        e = Point((width*0.34).toInt(), (width*0.65).toInt())
        radiusDE = Functions.curvedPath(d,e,unit*2,false)
        f = Point((width*0.28).toInt(), (width*0.71).toInt())
        radiusEF = Functions.curvedPath(e,f,unit*2,true)
        g = Point((width*0.22).toInt(), (width*0.71).toInt())
        radiusFG = Functions.curvedPath(f,g,unit,true)
        h = Point((width*0.23).toInt(), (width*0.675).toInt())
        radiusGH = Functions.curvedPath(g,h,unit*5,true)
        i = Point((width*0.23).toInt(), (width*0.665).toInt())
        radiusHI = Functions.curvedPath(h,i,unit*3,false)
        j = Point((width*0.2).toInt(), (width*0.65).toInt())
        radiusIJ = Functions.curvedPath(i,j,unit,true)
        k = Point((width*0.22).toInt(), (width*0.63).toInt())
        radiusJK = Functions.curvedPath(j,k,unit*3,true)
        l = Point((width*0.225).toInt(), (width*0.62).toInt())
        radiusKL = Functions.curvedPath(k,l,unit*5,false)
        m = Point((width*0.24).toInt(), (width*0.6).toInt())
        radiusLM = Functions.curvedPath(l,m,unit*4,true)
        n = Point((width*0.27).toInt(), (width*0.58).toInt())
        radiusMN = Functions.curvedPath(m,n,unit*2,true)
        val o = Point((width*0.32).toInt(), (width*0.58).toInt())
        val radiusNO = Functions.curvedPath(n,o,unit*2,true)
        val radiusOA = Functions.curvedPath(o,a,unit/2,false)

        val pathArm2 = Path()
        pathArm2.moveTo(a.x.toFloat(), a.y.toFloat())
        pathArm2.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathArm2.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathArm2.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathArm2.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        pathArm2.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathArm2.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathArm2.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        pathArm2.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathArm2.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        pathArm2.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathArm2.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKL.x,radiusKL.y, l.x.toFloat(), l.y.toFloat())
        pathArm2.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        pathArm2.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        pathArm2.cubicTo(n.x.toFloat(), n.y.toFloat(),radiusNO.x,radiusNO.y, o.x.toFloat(), o.y.toFloat())
        pathArm2.cubicTo(o.x.toFloat(), o.y.toFloat(),radiusOA.x,radiusOA.y, a.x.toFloat(), a.y.toFloat())

        canvas.drawPath(pathArm2,paint)

    }

    private fun drawBasketDownHandle(canvas: Canvas){
        paint.style = Paint.Style.FILL_AND_STROKE
        paint.strokeWidth = (unit/2).toFloat()

        val a = Point((width*0.27).toInt(), (width*0.715).toInt())
        val b = Point((width*0.27).toInt(), (width*0.76).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*2,false)
        val c = Point((width*0.09).toInt(), (width*0.67).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit,false)
        val d = Point((width*0.14).toInt(), (width*0.585).toInt())
        val radiusCD = Functions.curvedPath(c,d,unit,false)
        val e = Point((width*0.17).toInt(), (width*0.56).toInt())
        val radiusDE = Functions.curvedPath(d,e,unit*3,false)
        val f = Point((width*0.24).toInt(), (width*0.56).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit,false)
        val g = Point((width*0.275).toInt(), (width*0.58).toInt())
        val radiusFG = Functions.curvedPath(f,g,unit,true)
        val h = Point((width*0.23).toInt(), (width*0.59).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit,false)
        val i = Point((width*0.14).toInt(), (width*0.66).toInt())
        val radiusHI = Functions.curvedPath(h,i,unit*5,false)
        val j = Point((width*0.15).toInt(), (width*0.68).toInt())
        val radiusIJ = Functions.curvedPath(i,j,unit,false)
        val k = Point((width*0.21).toInt(), (width*0.7).toInt())
        val radiusJK = Functions.curvedPath(j,k,unit,true)
        val radiusKA = Functions.curvedPath(k,a,unit,false)


        val pathBasketHandle1 = Path()
        pathBasketHandle1.moveTo(a.x.toFloat(), a.y.toFloat())
        pathBasketHandle1.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathBasketHandle1.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathBasketHandle1.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathBasketHandle1.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        pathBasketHandle1.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathBasketHandle1.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathBasketHandle1.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        pathBasketHandle1.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathBasketHandle1.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        pathBasketHandle1.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathBasketHandle1.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKA.x,radiusKA.y, a.x.toFloat(), a.y.toFloat())
        pathBasketHandle1.close()
        canvas.drawPath(pathBasketHandle1,paint)

    }

    private fun drawArmsUp(canvas: Canvas){
        paint.style = Paint.Style.STROKE

        paint.strokeWidth = (unit*1.5).toFloat()

        var a = Point((width*0.2).toInt(), (width*0.07).toInt())
        var b = Point((width*0.15).toInt(), (width*0.1).toInt())
        var radiusAB = Functions.curvedPath(a,b,unit*2,false)
        var c = Point((width*0.17).toInt(), (width*0.13).toInt())
        var radiusBC = Functions.curvedPath(b,c,unit*2,false)
        var d = Point((width*0.2).toInt(), (width*0.115).toInt())
        var radiusCD = Functions.curvedPath(c,d,unit,true)
        val radiusDA = Functions.curvedPath(d,a,unit*2,false)
        var e = Point((width*0.19).toInt(), (width*0.17).toInt())
        val radiusCE = Functions.curvedPath(c,e,unit,false)
        var f = Point((width*0.24).toInt(), (width*0.15).toInt())
        var radiusEF = Functions.curvedPath(e,f,unit,true)
        var g = Point((width*0.24).toInt(), (width*0.125).toInt())
        var radiusFG = Functions.curvedPath(f,g,unit/2,true)
        val radiusGD = Functions.curvedPath(g,d,unit,false)
        var h = Point((width*0.215).toInt(), (width*0.2).toInt())
        val radiusEH = Functions.curvedPath(e,h,unit,false)
        var i = Point((width*0.25).toInt(), (width*0.18).toInt())
        var radiusHI = Functions.curvedPath(h,i,unit,true)
        val radiusIF = Functions.curvedPath(i,f,unit/2,true)
        var j = Point((width*0.25).toInt(), (width*0.07).toInt())
        val radiusDJ = Functions.curvedPath(d,j,unit*2,true)
        var k = Point((width*0.3).toInt(), (width*0.09).toInt())
        var radiusJK = Functions.curvedPath(j,k,unit*2,true)
        var l = Point((width*0.365).toInt(), (width*0.27).toInt())
        var m = Point((width*0.345).toInt(), (width*0.285).toInt())
        var radiusLM = Functions.curvedPath(l,m,unit*7,true)
        var n = Point((width*0.3).toInt(), (width*0.21).toInt())
        var radiusMN = Functions.curvedPath(m,n,unit,true)
        var o = Point((width*0.28).toInt(), (width*0.19).toInt())
        var radiusNO = Functions.curvedPath(n,o,unit,false)
        var p = Point((width*0.26).toInt(), (width*0.14).toInt())
        var radiusOP = Functions.curvedPath(o,p,unit,true)
        val radiusPD = Functions.curvedPath(p,d,unit*5,false)



        val pathHandUp = Path()
        pathHandUp.moveTo(a.x.toFloat(), a.y.toFloat())
        pathHandUp.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathHandUp.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathHandUp.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathHandUp.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDA.x,radiusDA.y, a.x.toFloat(), a.y.toFloat())
        pathHandUp.moveTo(c.x.toFloat(), c.y.toFloat())
        pathHandUp.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCE.x,radiusCE.y, e.x.toFloat(), e.y.toFloat())
        pathHandUp.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathHandUp.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathHandUp.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGD.x,radiusGD.y, d.x.toFloat(), d.y.toFloat())
        pathHandUp.moveTo(e.x.toFloat(), e.y.toFloat())
        pathHandUp.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEH.x,radiusEH.y, h.x.toFloat(), h.y.toFloat())
        pathHandUp.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathHandUp.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIF.x,radiusIF.y, f.x.toFloat(), f.y.toFloat())
        pathHandUp.moveTo(d.x.toFloat(), d.y.toFloat())
        pathHandUp.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDJ.x,radiusDJ.y, j.x.toFloat(), j.y.toFloat())
        pathHandUp.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathHandUp.lineTo(l.x.toFloat(), l.y.toFloat())
        pathHandUp.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        pathHandUp.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        pathHandUp.cubicTo(n.x.toFloat(), n.y.toFloat(),radiusNO.x,radiusNO.y, o.x.toFloat(), o.y.toFloat())
        pathHandUp.cubicTo(o.x.toFloat(), o.y.toFloat(),radiusOP.x,radiusOP.y, p.x.toFloat(), p.y.toFloat())
        pathHandUp.cubicTo(p.x.toFloat(), p.y.toFloat(),radiusPD.x,radiusPD.y, d.x.toFloat(), d.y.toFloat())


        canvas.drawPath(pathHandUp,paint)


        a = Point((width*0.16).toInt(), (width*0.275).toInt())
        b = Point((width*0.235).toInt(), (width*0.26).toInt())
        radiusAB = Functions.curvedPath(a,b,unit*8,false)
        c = Point((width*0.24).toInt(), (width*0.22).toInt())
        radiusBC = Functions.curvedPath(b,c,unit,true)
        d = Point((width*0.25).toInt(), (width*0.22).toInt())
        radiusCD = Functions.curvedPath(c,d,unit,true)
        e = Point((width*0.27).toInt(), (width*0.28).toInt())
        val radiusDE = Functions.curvedPath(d,e,unit,true)
        f = Point((width*0.3).toInt(), (width*0.33).toInt())
        radiusEF = Functions.curvedPath(e,f,unit/2,false)
        g = Point((width*0.31).toInt(), (width*0.34).toInt())
        radiusFG = Functions.curvedPath(f,g,unit/2,false)
        h = Point((width*0.42).toInt(), (width*0.41).toInt())
        i = Point((width*0.41).toInt(), (width*0.43).toInt())
        radiusHI = Functions.curvedPath(h,i,unit*11,true)
        j = Point((width*0.34).toInt(), (width*0.4).toInt())
        k = Point((width*0.2).toInt(), (width*0.39).toInt())
        radiusJK = Functions.curvedPath(j,k,unit*2,false)
        l = Point((width*0.14).toInt(), (width*0.39).toInt())
        val radiusKL = Functions.curvedPath(k,l,unit,true)
        m = Point((width*0.155).toInt(), (width*0.375).toInt())
        radiusLM = Functions.curvedPath(l,m,unit*4,true)
        n = Point((width*0.12).toInt(), (width*0.34).toInt())
        radiusMN = Functions.curvedPath(m,n,unit,true)
        o = Point((width*0.135).toInt(), (width*0.325).toInt())
        radiusNO = Functions.curvedPath(n,o,unit*5,true)
        p = Point((width*0.16).toInt(), (width*0.34).toInt())
        radiusOP = Functions.curvedPath(o,p,1.0,true)
        val q = Point((width*0.165).toInt(), (width*0.335).toInt())
        val radiusPQ = Functions.curvedPath(p,q,unit*3,false)
        val r = Point((width*0.135).toInt(), (width*0.305).toInt())
        val radiusQR = Functions.curvedPath(q,r,1.0,false)
        val radiusRA = Functions.curvedPath(r,a,unit*9,true)


        val pathHandDown = Path()
        pathHandDown.moveTo(a.x.toFloat(), a.y.toFloat())
        pathHandDown.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathHandDown.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathHandDown.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathHandDown.cubicTo(d.x.toFloat(), d.y.toFloat(),radiusDE.x,radiusDE.y, e.x.toFloat(), e.y.toFloat())
        pathHandDown.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathHandDown.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathHandDown.lineTo(h.x.toFloat(), h.y.toFloat())
        pathHandDown.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathHandDown.lineTo(j.x.toFloat(), j.y.toFloat())
        pathHandDown.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathHandDown.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKL.x,radiusKL.y, l.x.toFloat(), l.y.toFloat())
        pathHandDown.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        pathHandDown.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        pathHandDown.cubicTo(n.x.toFloat(), n.y.toFloat(),radiusNO.x,radiusNO.y, o.x.toFloat(), o.y.toFloat())
        pathHandDown.cubicTo(o.x.toFloat(), o.y.toFloat(),radiusOP.x,radiusOP.y, p.x.toFloat(), p.y.toFloat())
        pathHandDown.cubicTo(p.x.toFloat(), p.y.toFloat(),radiusPQ.x,radiusPQ.y, q.x.toFloat(), q.y.toFloat())
        pathHandDown.cubicTo(q.x.toFloat(), q.y.toFloat(),radiusQR.x,radiusQR.y, r.x.toFloat(), r.y.toFloat())
        pathHandDown.cubicTo(r.x.toFloat(), r.y.toFloat(),radiusRA.x,radiusRA.y, a.x.toFloat(), a.y.toFloat())
        pathHandDown.close()

        canvas.drawPath(pathHandDown,paint)

    }

    private fun drawBasketUp(canvas: Canvas){
        paint.style = Paint.Style.FILL_AND_STROKE
        paint.strokeWidth = (unit/2).toFloat()

        val a = Point((width*0.09).toInt(), (width*0.21).toInt())
        val b = Point((width*0.09).toInt(), (width*0.04).toInt())
        val radiusAB = Functions.curvedPath(a,b,unit*3,true)
        val c = Point((width*0.2).toInt(), (width*0.05).toInt())
        val radiusBC = Functions.curvedPath(b,c,unit*5,true)
        val d = Point((width*0.22).toInt(), (width*0.08).toInt())
        val radiusCD = Functions.curvedPath(c,d,0.0,true)
        val e = Point((width*0.21).toInt(), (width*0.09).toInt())
        val f = Point((width*0.18).toInt(), (width*0.07).toInt())
        val radiusEF = Functions.curvedPath(e,f,unit*2,false)
        val g = Point((width*0.125).toInt(), (width*0.055).toInt())
        val radiusFG = Functions.curvedPath(f,g,unit*2,false)
        val h = Point((width*0.11).toInt(), (width*0.13).toInt())
        val radiusGH = Functions.curvedPath(g,h,unit*2,false)
        val i = Point((width*0.125).toInt(), (width*0.2).toInt())
        val radiusHI = Functions.curvedPath(h,i,unit/2,false)
        val j = Point((width*0.14).toInt(), (width*0.21).toInt())
        val radiusIJ = Functions.curvedPath(i,j,unit,false)
        val k = Point((width*0.2).toInt(), (width*0.19).toInt())
        val radiusJK = Functions.curvedPath(j,k,unit,true)
        val l = Point((width*0.21).toInt(), (width*0.2).toInt())
        val radiusKL = Functions.curvedPath(k,l,unit/2,false)
        val m = Point((width*0.25).toInt(), (width*0.18).toInt())
        val radiusLM = Functions.curvedPath(l,m,unit,true)
        val n = Point((width*0.245).toInt(), (width*0.115).toInt())
        val radiusMN = Functions.curvedPath(m,n,unit,true)
        val o = Point((width*0.28).toInt(), (width*0.19).toInt())
        val p = Point((width*0.34).toInt(), (width*0.28).toInt())
        val q = Point((width*0.3).toInt(), (width*0.33).toInt())
        val radiusPQ = Functions.curvedPath(p,q,unit,true)
        val r = Point((width*0.27).toInt(), (width*0.28).toInt())
        val radiusQR = Functions.curvedPath(q,r,unit,true)
        val s = Point((width*0.25).toInt(), (width*0.22).toInt())
        val radiusRS = Functions.curvedPath(r,s,unit,false)
        val t = Point((width*0.24).toInt(), (width*0.22).toInt())
        val radiusST = Functions.curvedPath(s,t,unit,false)
        val u = Point((width*0.235).toInt(), (width*0.26).toInt())
        val radiusTU = Functions.curvedPath(t,u,unit,false)
        val v = Point((width*0.16).toInt(), (width*0.275).toInt())
        val radiusUV = Functions.curvedPath(u,v,unit*8,true)
        val w = Point((width*0.135).toInt(), (width*0.305).toInt())
        val radiusVW = Functions.curvedPath(v,w,unit*9,false)
        val x = Point((width*0.165).toInt(), (width*0.335).toInt())
        val radiusWX = Functions.curvedPath(w,x,0.0,false)
        val y = Point((width*0.135).toInt(), (width*0.325).toInt())
        val radiusXY = Functions.curvedPath(x,y,0.0,true)
        val z = Point((width*0.12).toInt(), (width*0.34).toInt())
        val radiusYZ = Functions.curvedPath(y,z,unit*5,false)
        val a1 = Point((width*0.145).toInt(), (width*0.4).toInt())
        val b1 = Point((width*0.05).toInt(), (width*0.33).toInt())
        val radiusAB1 = Functions.curvedPath(a1,b1,unit*2,true)
        val c1 = Point((width*0.03).toInt(), (width*0.27).toInt())
        val radiusBC1 = Functions.curvedPath(b1,c1,unit*2,true)
        val d1 = Point((width*0.05).toInt(), (width*0.245).toInt())
        val radiusCD1 = Functions.curvedPath(c1,d1,unit,true)
        val e1 = Point((width*0.09).toInt(), (width*0.23).toInt())
        val radiusDE1 = Functions.curvedPath(d1,e1,0.0,false)
        val radiusEA1 = Functions.curvedPath(e1,a,unit,false)


        val pathBasketUp = Path()
        pathBasketUp.moveTo(a.x.toFloat(), a.y.toFloat())
        pathBasketUp.cubicTo(a.x.toFloat(), a.y.toFloat(),radiusAB.x,radiusAB.y, b.x.toFloat(), b.y.toFloat())
        pathBasketUp.cubicTo(b.x.toFloat(), b.y.toFloat(),radiusBC.x,radiusBC.y, c.x.toFloat(), c.y.toFloat())
        pathBasketUp.cubicTo(c.x.toFloat(), c.y.toFloat(),radiusCD.x,radiusCD.y, d.x.toFloat(), d.y.toFloat())
        pathBasketUp.lineTo(e.x.toFloat(), e.y.toFloat())
        pathBasketUp.cubicTo(e.x.toFloat(), e.y.toFloat(),radiusEF.x,radiusEF.y, f.x.toFloat(), f.y.toFloat())
        pathBasketUp.cubicTo(f.x.toFloat(), f.y.toFloat(),radiusFG.x,radiusFG.y, g.x.toFloat(), g.y.toFloat())
        pathBasketUp.cubicTo(g.x.toFloat(), g.y.toFloat(),radiusGH.x,radiusGH.y, h.x.toFloat(), h.y.toFloat())
        pathBasketUp.cubicTo(h.x.toFloat(), h.y.toFloat(),radiusHI.x,radiusHI.y, i.x.toFloat(), i.y.toFloat())
        pathBasketUp.cubicTo(i.x.toFloat(), i.y.toFloat(),radiusIJ.x,radiusIJ.y, j.x.toFloat(), j.y.toFloat())
        pathBasketUp.cubicTo(j.x.toFloat(), j.y.toFloat(),radiusJK.x,radiusJK.y, k.x.toFloat(), k.y.toFloat())
        pathBasketUp.cubicTo(k.x.toFloat(), k.y.toFloat(),radiusKL.x,radiusKL.y, l.x.toFloat(), l.y.toFloat())
        pathBasketUp.cubicTo(l.x.toFloat(), l.y.toFloat(),radiusLM.x,radiusLM.y, m.x.toFloat(), m.y.toFloat())
        pathBasketUp.cubicTo(m.x.toFloat(), m.y.toFloat(),radiusMN.x,radiusMN.y, n.x.toFloat(), n.y.toFloat())
        pathBasketUp.lineTo(o.x.toFloat(), o.y.toFloat())
        pathBasketUp.lineTo(p.x.toFloat(), p.y.toFloat())
        pathBasketUp.cubicTo(p.x.toFloat(), p.y.toFloat(),radiusPQ.x,radiusPQ.y, q.x.toFloat(), q.y.toFloat())
        pathBasketUp.cubicTo(q.x.toFloat(), q.y.toFloat(),radiusQR.x,radiusQR.y, r.x.toFloat(), r.y.toFloat())
        pathBasketUp.cubicTo(r.x.toFloat(), r.y.toFloat(),radiusRS.x,radiusRS.y, s.x.toFloat(), s.y.toFloat())
        pathBasketUp.cubicTo(s.x.toFloat(), s.y.toFloat(),radiusST.x,radiusST.y, t.x.toFloat(), t.y.toFloat())
        pathBasketUp.cubicTo(t.x.toFloat(), t.y.toFloat(),radiusTU.x,radiusTU.y, u.x.toFloat(), u.y.toFloat())
        pathBasketUp.cubicTo(u.x.toFloat(), u.y.toFloat(),radiusUV.x,radiusUV.y, v.x.toFloat(), v.y.toFloat())
        pathBasketUp.cubicTo(v.x.toFloat(), v.y.toFloat(),radiusVW.x,radiusVW.y, w.x.toFloat(), w.y.toFloat())
        pathBasketUp.cubicTo(w.x.toFloat(), w.y.toFloat(),radiusWX.x,radiusWX.y, x.x.toFloat(), x.y.toFloat())
        pathBasketUp.cubicTo(x.x.toFloat(), x.y.toFloat(),radiusXY.x,radiusXY.y, y.x.toFloat(), y.y.toFloat())
        pathBasketUp.cubicTo(y.x.toFloat(), y.y.toFloat(),radiusYZ.x,radiusYZ.y, z.x.toFloat(), z.y.toFloat())
        pathBasketUp.lineTo(a1.x.toFloat(), a1.y.toFloat())
        pathBasketUp.cubicTo(a1.x.toFloat(), a1.y.toFloat(),radiusAB1.x,radiusAB1.y, b1.x.toFloat(), b1.y.toFloat())
        pathBasketUp.cubicTo(b1.x.toFloat(), b1.y.toFloat(),radiusBC1.x,radiusBC1.y, c1.x.toFloat(), c1.y.toFloat())
        pathBasketUp.cubicTo(c1.x.toFloat(), c1.y.toFloat(),radiusCD1.x,radiusCD1.y, d1.x.toFloat(), d1.y.toFloat())
        pathBasketUp.cubicTo(d1.x.toFloat(), d1.y.toFloat(),radiusDE1.x,radiusDE1.y, e1.x.toFloat(), e1.y.toFloat())
        pathBasketUp.cubicTo(e1.x.toFloat(), e1.y.toFloat(),radiusEA1.x,radiusEA1.y, a.x.toFloat(), a.y.toFloat())
        pathBasketUp.close()

        canvas.drawPath(pathBasketUp,paint)

    }


    override fun setAlpha(alpha: Int) {
        paint.alpha=alpha
    }

    override fun getOpacity(): Int = PixelFormat.OPAQUE

    override fun setColorFilter(colorFilter: ColorFilter?) {
        paint.colorFilter = colorFilter
    }


}